# .golangci.yml configuration file for redrip
# See https://golangci-lint.run/usage/configuration/ for more information

# Required version configuration
version: "2"

run:
  timeout: 5m # Timeout for running linters

linters:
  enable:
    - errcheck
    - govet
    - ineffassign
    - staticcheck
    - unused
    - misspell
    - revive

issues:
  max-issues-per-linter: 0
  max-same-issues: 0 