name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.24.2'
          cache: true

      - name: Format
        run: |
          go fmt ./...
          if [ -n "$(git status --porcelain)" ]; then
            if [[ "${{ github.event_name }}" == "pull_request" ]]; then
              echo "::error::Code formatting issues found. Please run 'go fmt ./...' and commit changes."
              exit 1
            else
              echo "Automatically fixing formatting issues and committing changes..."
              git config --local user.email "action@github.com"
              git config --local user.name "GitHub Action"
              git add .
              git commit -m "Auto-format code with go fmt"
              
              # Only try to push if running in GitHub Actions (not in local act environment)
              if [[ -n "$GITHUB_ACTIONS" && "$GITHUB_ACTIONS" == "true" ]]; then
                # Don't fail the workflow if push fails
                git push || echo "Push failed but continuing workflow"
              else
                echo "Running in local environment, skipping push"
              fi
              
              echo "Code formatting issues fixed and changes committed."
            fi
          else
            echo "No formatting issues found."
          fi

      - name: Simple Go vet
        run: |
          echo "Running basic Go vet instead of golangci-lint"
          go vet ./...

      - name: Test
        run: |
          go test -v -race -coverprofile=coverage.txt -covermode=atomic ./...

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3
        with:
          file: ./coverage.txt
          fail_ci_if_error: false

  build:
    name: Build
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.21'
          cache: true

      - name: Build
        run: go build -v -o redrip ./cmd 